{% set name = "wagtail-seo" %}
{% set version = "2.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail-seo-{{ version }}.tar.gz
  sha256: fd9ff0f840a2800f30421182bd101615da236bc8431227f9aeb19bcc7adb87ac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - wagtail >=3.0,<6.0

test:
  imports:
    - wagtailseo

about:
  home: https://github.com/coderedcorp/wagtail-seo
  summary: Search engine and social media optimization for Wagtail.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
