{% set name = "wagtail-seo" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coderedcorp/wagtail-seo/archive/v{{ version }}.tar.gz
  sha256: 374b7617c67c845171ef8b08339621d9d2c9e01aad7df66340e8aeedf6aaee24

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - wagtail >=3.0,<7.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - wagtailseo

about:
  home: https://github.com/coderedcorp/wagtail-seo
  summary: Search engine and social media optimization for Wagtail.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
