{% set name = "wagtail-seo" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coderedcorp/wagtail-seo/archive/v{{ version }}.tar.gz
  sha256: 8d7c6e61135d73a82716eff77d4981e446049ccdad0d92ac31faa98de6d85215

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - wagtail >=4.0,<7

test:
  imports:
    - wagtailseo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/coderedcorp/wagtail-seo
  summary: Search engine and social media optimization for Wagtail.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
